name: CI

# Triggers the workflow on push or pull request.
on:
  push:
    paths-ignore:
    - 'sql/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'sql/**'
    - '**.md'

# Build Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      # Prep phase
      - run: mkdir esx-1-1 esx-1-2
      
      # Build source
      - run: cd src_htmlPhone && npm ci && npm run build
      
      # Create a base resource for each ESX version
      - run: cp -a resources/. esx-1-1/
      - run: cp -a resources/. esx-1-2/
        
      # Add SQL Files
      - run: cp *.sql esx-1-1/ && cp *.sql esx-1-2/
      
      # Configure server.lua for each ESX Version
      - run: mv esx-1-1/server\ 1-1/server.lua esx-1-1/gcphone/server/server.lua
      - run: mv esx-1-2/server\ 1-2/server.lua esx-1-2/gcphone/server/server.lua
      
      # Cleanup
      - run: rm -r esx-1-1/server\ 1-1/ esx-1-1/server\ 1-2/
      - run: rm -r esx-1-2/server\ 1-1/ esx-1-2/server\ 1-2/
      
      # Enable ESX 1.2 in gcphone/config.lua for ESX 1.2 resource
      - run: sed -i 's/Config.newESX = false/Config.newESX = true/g' esx-1-2/gcphone/config.lua
      
      # Upload Artifacts for ESX 1.1 and ESX 1.2
      - uses: actions/upload-artifact@master
        with:
          name: resources-esx-1-1
          path: esx-1-1
      - uses: actions/upload-artifact@master
        with:
          name: resources-esx-1-2
          path: esx-1-2
